# Integrantes: Juan Camilo Ortiz Garcia, Juan Idarraga, Juan Pablo Larrea
# Datos de prueba propios  (Parcial 1 - Programación 3)

defmodule Datos do
  def recolectores do
    [
      %{codigo: "R01", nombre: "Luz Marina Ospina", alimentacion: true},
      %{codigo: "R02", nombre: "Jhon Fredy Castaño", alimentacion: false},
      %{codigo: "R03", nombre: "Dora Cardona", alimentacion: true},
      %{codigo: "R04", nombre: "Wilson Arango", alimentacion: false},
      %{codigo: "R05", nombre: "Gloria Patricia Henao", alimentacion: true},
      %{codigo: "R06", nombre: "Carlos Andrés Villada", alimentacion: false},
      %{codigo: "R07", nombre: "Marleny Gómez", alimentacion: true},
      %{codigo: "R08", nombre: "Óscar Darío Restrepo", alimentacion: false},
      %{codigo: "R09", nombre: "Yolanda Betancur", alimentacion: true},
      %{codigo: "R10", nombre: "Hernán Giraldo", alimentacion: false},
      %{codigo: "R11", nombre: "Sandra Milena Toro", alimentacion: true},
      %{codigo: "R12", nombre: "Julián Esteban Marín", alimentacion: false}
    ]
  end

  def lotes do
    [
      %{id: "L1", nombre: "El Mirador", hectareas: 2.5},
      %{id: "L2", nombre: "La Cañada", hectareas: 1.5},
      %{id: "L3", nombre: "Buenavista", hectareas: 3.0},
      %{id: "L4", nombre: "El Cafetal", hectareas: 2.0}
    ]
  end

  def pesajes do
    [
      %{recolector: "R01", lote: "L3", dia: 1, kilos: 40, verdes: 5},
      %{recolector: "R01", lote: "L4", dia: 2, kilos: 35, verdes: 15},
      %{recolector: "R01", lote: "L4", dia: 3, kilos: 105, verdes: 5},
      %{recolector: "R01", lote: "L2", dia: 4, kilos: 105, verdes: 3},
      %{recolector: "R01", lote: "L1", dia: 5, kilos: 52.5, verdes: 4},
      %{recolector: "R01", lote: "L1", dia: 5, kilos: 42.5, verdes: 3},
      %{recolector: "R01", lote: "L2", dia: 1, kilos: 68, verdes: 12},
      %{recolector: "R01", lote: "L4", dia: 3, kilos: 75, verdes: 10},
      %{recolector: "R02", lote: "L4", dia: 1, kilos: 68, verdes: 5},
      %{recolector: "R02", lote: "L3", dia: 2, kilos: 75, verdes: 1},
      %{recolector: "R02", lote: "L1", dia: 3, kilos: 75, verdes: 7.5},
      %{recolector: "R02", lote: "L3", dia: 4, kilos: 88, verdes: 5},
      %{recolector: "R02", lote: "L3", dia: 5, kilos: 40, verdes: 4},
      %{recolector: "R02", lote: "L1", dia: 5, kilos: 50, verdes: 4},
      %{recolector: "R02", lote: "L2", dia: 5, kilos: 88, verdes: 2.5},
      %{recolector: "R02", lote: "L3", dia: 1, kilos: 75, verdes: 7.5},
      %{recolector: "R03", lote: "L3", dia: 1, kilos: 52.5, verdes: 15},
      %{recolector: "R03", lote: "L1", dia: 2, kilos: 40, verdes: 9},
      %{recolector: "R03", lote: "L1", dia: 3, kilos: 64.5, verdes: 5},
      %{recolector: "R03", lote: "L2", dia: 4, kilos: 105, verdes: 5},
      %{recolector: "R03", lote: "L4", dia: 5, kilos: 64.5, verdes: 6},
      %{recolector: "R03", lote: "L1", dia: 6, kilos: 42.5, verdes: 6},
      %{recolector: "R03", lote: "L2", dia: 4, kilos: 75, verdes: 9},
      %{recolector: "R03", lote: "L2", dia: 5, kilos: 60, verdes: 6},
      %{recolector: "R04", lote: "L4", dia: 1, kilos: 68, verdes: 2},
      %{recolector: "R04", lote: "L3", dia: 2, kilos: 60, verdes: 10},
      %{recolector: "R04", lote: "L3", dia: 3, kilos: 80, verdes: 5},
      %{recolector: "R04", lote: "L4", dia: 4, kilos: 88, verdes: 12},
      %{recolector: "R04", lote: "L2", dia: 5, kilos: 80, verdes: 12},
      %{recolector: "R04", lote: "L2", dia: 5, kilos: 50, verdes: 6},
      %{recolector: "R04", lote: "L1", dia: 5, kilos: 105, verdes: 0},
      %{recolector: "R04", lote: "L4", dia: 4, kilos: 60, verdes: 3},
      %{recolector: "R05", lote: "L4", dia: 1, kilos: 80, verdes: 3},
      %{recolector: "R05", lote: "L2", dia: 2, kilos: 40, verdes: 2},
      %{recolector: "R05", lote: "L3", dia: 3, kilos: 64.5, verdes: 15},
      %{recolector: "R05", lote: "L1", dia: 4, kilos: 75, verdes: 1.5},
      %{recolector: "R05", lote: "L4", dia: 5, kilos: 80, verdes: 0},
      %{recolector: "R05", lote: "L2", dia: 4, kilos: 80, verdes: 7.5},
      %{recolector: "R05", lote: "L4", dia: 1, kilos: 88, verdes: 15},
      %{recolector: "R06", lote: "L1", dia: 1, kilos: 105, verdes: 7.5},
      %{recolector: "R06", lote: "L4", dia: 2, kilos: 95, verdes: 12},
      %{recolector: "R06", lote: "L1", dia: 3, kilos: 80, verdes: 10},
      %{recolector: "R06", lote: "L2", dia: 4, kilos: 64.5, verdes: 1.5},
      %{recolector: "R06", lote: "L3", dia: 5, kilos: 88, verdes: 2},
      %{recolector: "R06", lote: "L1", dia: 5, kilos: 50, verdes: 7.5},
      %{recolector: "R06", lote: "L2", dia: 1, kilos: 45, verdes: 7.5},
      %{recolector: "R06", lote: "L2", dia: 5, kilos: 64.5, verdes: 6},
      %{recolector: "R08", lote: "L2", dia: 1, kilos: 88, verdes: 4},
      %{recolector: "R08", lote: "L1", dia: 2, kilos: 35, verdes: 2},
      %{recolector: "R08", lote: "L2", dia: 3, kilos: 105, verdes: 1.5},
      %{recolector: "R08", lote: "L2", dia: 4, kilos: 35, verdes: 9},
      %{recolector: "R08", lote: "L4", dia: 5, kilos: 88, verdes: 15},
      %{recolector: "R08", lote: "L4", dia: 1, kilos: 105, verdes: 2},
      %{recolector: "R08", lote: "L2", dia: 4, kilos: 80, verdes: 10},
      %{recolector: "R09", lote: "L2", dia: 1, kilos: 60, verdes: 1.5},
      %{recolector: "R09", lote: "L2", dia: 2, kilos: 68, verdes: 1.5},
      %{recolector: "R09", lote: "L1", dia: 3, kilos: 60, verdes: 5},
      %{recolector: "R09", lote: "L2", dia: 4, kilos: 80, verdes: 12},
      %{recolector: "R09", lote: "L2", dia: 5, kilos: 75, verdes: 2.5},
      %{recolector: "R09", lote: "L4", dia: 5, kilos: 50, verdes: 1.5},
      %{recolector: "R09", lote: "L3", dia: 1, kilos: 68, verdes: 6},
      %{recolector: "R09", lote: "L2", dia: 2, kilos: 80, verdes: 5},
      %{recolector: "R10", lote: "L2", dia: 1, kilos: 35, verdes: 3},
      %{recolector: "R10", lote: "L2", dia: 2, kilos: 45, verdes: 3},
      %{recolector: "R10", lote: "L3", dia: 3, kilos: 88, verdes: 9},
      %{recolector: "R10", lote: "L1", dia: 4, kilos: 95, verdes: 12},
      %{recolector: "R10", lote: "L3", dia: 5, kilos: 88, verdes: 2},
      %{recolector: "R10", lote: "L1", dia: 5, kilos: 30, verdes: 7.5},
      %{recolector: "R10", lote: "L2", dia: 1, kilos: 64.5, verdes: 2.5},
      %{recolector: "R10", lote: "L1", dia: 5, kilos: 88, verdes: 12},
      %{recolector: "R05", lote: "L2", dia: 6, kilos: 100, verdes: 2},
      %{recolector: "R08", lote: "L3", dia: 6, kilos: 100, verdes: 3},
      %{recolector: "R07", lote: "L1", dia: 1, kilos: 240, verdes: 9},
      %{recolector: "R07", lote: "L2", dia: 2, kilos: 20, verdes: 0},
      %{recolector: "R07", lote: "L3", dia: 3, kilos: 25, verdes: 1},
      %{recolector: "R07", lote: "L4", dia: 4, kilos: 30, verdes: 0},
      %{recolector: "R07", lote: "L1", dia: 5, kilos: 45, verdes: 2},
      %{recolector: "R07", lote: "L2", dia: 6, kilos: 35, verdes: 0.5},
      %{recolector: "R07", lote: "L3", dia: 2, kilos: 22, verdes: 0},
      %{recolector: "R11", lote: "L1", dia: 2, kilos: 110, verdes: 1},
      %{recolector: "R11", lote: "L3", dia: 4, kilos: 75, verdes: 3},
      # --- Pesajes inválidos a propósito ---
      %{recolector: "R99", lote: "L1", dia: 1, kilos: 80, verdes: 3},
      %{recolector: "R98", lote: "L2", dia: 3, kilos: 60, verdes: 2},
      %{recolector: "R01", lote: "L9", dia: 2, kilos: 50, verdes: 2},
      %{recolector: "R03", lote: "L7", dia: 4, kilos: 45, verdes: 3},
      %{recolector: "R04", lote: "L3", dia: 7, kilos: 300, verdes: 3},
      %{recolector: "R06", lote: "L2", dia: 0, kilos: 70, verdes: 4},
      %{recolector: "R09", lote: "L1", dia: 2.5, kilos: 55, verdes: 2},
      %{recolector: "R02", lote: "L2", dia: 3, kilos: 0, verdes: 4},
      %{recolector: "R05", lote: "L3", dia: 5, kilos: 300, verdes: 2},
      %{recolector: "R08", lote: "L1", dia: 4, kilos: -5, verdes: 3},
      %{recolector: "R01", lote: "L2", dia: 3, kilos: 40, verdes: 130},
      %{recolector: "R10", lote: "L4", dia: 5, kilos: 60, verdes: -2},
      %{recolector: "R12", lote: "L1", dia: 2, kilos: 251, verdes: 3}
    ]
  end
end
